version: "3.8"

services:
  mysql:
    image: mysql
    restart: always
    # build:
    #   context: ./mysql
    ports:
      - 3306:3306
    environment:
      # - mysql_USER=
      # - mysql_PASSWORD=123456789
      # - mysql_MYSQL_LOCALHOST_USER=caradmin
      - MYSQL_DATABASE=xmpp_demo
      # - mysql_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=123456789
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  mysql:
  mysql_config:
